name: Deploy Next.js Application

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: ðŸŽ‰ Deploy
    runs-on: ubuntu-latest
    steps:
      - name: ðŸšš Get latest code
        uses: actions/checkout@v2

      - name: ðŸ“‚ Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'

      - name: ðŸ“‚ Clone or update repository on remote server
        uses: appleboy/ssh-action@master
        with:
          host: 65.1.1.20
          username: ec2-user
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /usr/share/nginx/html/frontend-code || exit
            if [ ! -d ".git" ]; then
              git clone https://github.com/prashant2599/frontend-code.git .
            else
              git pull origin main
            fi
            ls -la

      - name: ðŸ›  Build and set ownership on remote server
        uses: appleboy/ssh-action@master
        with:
          host: 65.1.1.20
          username: ec2-user
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /usr/share/nginx/html/frontend-code || exit
            if [ -f "package.json" ]; then
              npm install
            fi
            sudo chown -R nginx:nginx /usr/share/nginx/html/frontend-code/
            sudo chmod -R 755 /usr/share/nginx/html/frontend-code/
            if [ -f "dev_run.sh" ]; then
              sudo chmod +x dev_run.sh
              ./dev_run.sh
            fi
